services:
  - type: web
    name: forestsnap-api
    env: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENWEATHER_API_KEY
        value: YOUR_API_KEY_HERE
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/server/data
      sizeGB: 1
